config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end
  
  def new
    @order = Order.new
  end
  
  def create
    @order = Order.new(order_params)
  
    render :create if @order.save
  end 
  
  
  private
    def order_params
      params.require(:order).permit(:name, :chanel, :amount)
    end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecpay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<form id="123" action="https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5" method="post">

  <input type="hidden" name="MerchantID" value="2000132">
  <input type="hidden" name="MerchantTradeNo" value="Ray8085">
  <input type="hidden" name="MerchantTradeDate" value="2021/05/17 11:40:00"> 
  <input type="hidden" name="PaymentType" value="aio">
  <input type="hidden" name="TotalAmount" value="5000">
  <input type="hidden" name="TradeDesc" value="123">
  <input type="hidden" name="ItemName" value="donate">
  <input type="hidden" name="ReturnURL" value="http://localhost:3000/orders/new">
  <input type="hidden" name="ChoosePayment" value="Credit">
  <input type="hidden" name="CheckMacValue" value="5592326F8B7B728937B71F2922929775C2D29A94C0B094A0324F112BC2C9282F">
  <input type="hidden" name="EncryptType" value="1">

</form>

<script>
  (function() {
    document.getElementById("123").submit()
  })()
</script>

app/views/orders/index.html.erb
<h1>歡迎贊助創作者</h1>

<%= link_to '捐起來！', new_order_path %>

app/views/orders/new.html.erb
<h1>贊助頁面</h1>

<%= form_for(@order) do |form| %>
<div>
<%= form.label :贊助人姓名 %>
<%= form.text_field :name %>
</div>

<div>
<%= form.label :贊助頻道 %>
<%= form.text_field :chanel %>
</div>

<div>
<%= form.label :贊助金額 %>
<%= form.text_field :amount %>
</div>

<%= form.submit :確定贊助%>

<% end %>